# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: xblog
email: ""
# this means to ignore newlines until "baseurl:"
description: >
  This is a Zhuyi Xue's blog and techinical notes.
baseurl: "" # the subpath of your site, e.g. /blog
# the base hostname & protocol for your site
url: "http://zyxue.github.io"
# twitter_username: jekyllrb
github_username:  zyxue

# Build settings
markdown: kramdown
